### ISSUE TITLE
NavX AHRS class no longer has a function to return Rotation2d

### ISSUE THREAD

**Issue by rzblue** [wpilibsuite/2024Beta#10]
`getRotation2d` was previously provided by the `Gyro` interface, it would be ideal if the AHRS class added this functionality back.

**Comment by Jm-Taylor** [comment]
Whoops, I will get on it.

**Comment by Jm-Taylor** [comment]
@rzblue @calcmogul, both functions have been added to v2024.0.1-beta-3. I personally don't know what to do with the data, but I checked, and it was outputting data on the calls.
