### ISSUE TITLE
DriverStation "Team Station" mapping to wrong alliance color

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/2024Beta#18]
`DriverStation.getAlliance()` is returning the wrong alliance color for `Red 1` and `Blue 1`. Selecting a value in DS returns these values:
- Red 1: Optional.empty
- Red 2: Optional[Red]
- Red 3: Optional[Red]
- Blue 1: Optional[Red]
- Blue 2:  Optional[Blue]
- Blue 3: Optional[Blue]

DS:  24.0b64
RIO:  roboRIO2_2024_v1.1
Lib:  Java 2024.1.1-beta-2

**Comment by ThadHouse** [comment]
This will be fixed in Beta 3.
