### ISSUE TITLE
Confusing dialog after installing vendordep

### ISSUE THREAD

**Issue by chauser** [wpilibsuite/2024Beta#26]
After adding a new online vendor dep (CTRE in my case but I don't think it matters) a dialog box appears offering to build the project with choices "Yes" "No" and "Cancel". It is unclear what the "Cancel" option would do.

**Comment by GrahamSH-LLK** [comment]
It seems to do absolutely nothing.

**Comment by chauser** [comment]
Thanks. Similar problem with the "Would you like to import this project into 2024?" dialog. Choices there are "No, Don't ask again", "No", "Cancel", "Yes".
