### ISSUE TITLE
DS Log file viewer bottom cut off

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/2024Beta#30]
In the DS Log Viewer, on Windows 11, the window is scaled so that the bottom is cut off, and there's no horizontal scroll bar. Resizing the window doesn't change anything as it adjusts the scaling.

![image](https://github.com/wpilibsuite/2024Beta/assets/4885091/4c6ac966-ddeb-47ad-87c3-0e1e2bb251a5)

**Comment by ThadHouse** [comment]
Do you have any dpi scaling on? I’ve noticed lots of labview stuff does not work right with any dpi scaling other than 100%

**Comment by sciencewhiz** [comment]
It happens at 100% also

**Comment by sciencewhiz** [comment]
This happens on beta 2 also

**Comment by sciencewhiz** [comment]
This was fixed in Game Tools 2024 Patch 1
