### ISSUE TITLE
CommandPS5Controller right joystick always returns -1

### ISSUE THREAD

**Issue by TapChap** [wpilibsuite/2024Beta#43]
* When using the methods getRightX() / getRightY() of a CommandPS5Controller object, the returned value is always stuck at -1.
* in the Driverstation Joystick view, everything seems good, 
* I'm using a PS5 controller IRL (obviously) 
* CommandPS4Controller works fine

I don't have access to a robot at the moment, but If needed i'll have access to one this Sunday (to provide, pictures / log files / code etc)

**Comment by TapChap** [comment]
CommandPS4Controller works fine

**Comment by ThadHouse** [comment]
It looks like our mapping might be wrong. The triggers and the right stick are swapped. So getLeftTrigger() and getRightTrigger() seem to return what the right stick should be.

**Comment by ThadHouse** [comment]
Actually, my controller seems to completely match PS4 controller mappings. 

https://github.com/wpilibsuite/allwpilib/pull/5257

Whoever was writing the PR did have different mappings for PS5 and PS4 controllers. So we need to figure out why.
