### ISSUE TITLE
Invalid Image Exception, roboRIO image is missing the FRC_ prefix

### ISSUE THREAD

**Issue by Jm-Taylor** [wpilibsuite/2024Beta#6]
When deploying

admin @ 172.22.11.2: Connected.
  Reason: InvalidImageException
  Could not parse image version!
/etc/natinst/share/scs_imagemetadata.ini contents:
[ImageMetadata]
IMAGEDESCRIPTION = ""
IMAGEID = "{979268BF-16F8-4042-BAA6-7AF50D001CEE}"
IMAGETITLE = "roboRIO2 Image"
IMAGEVERSION = "roboRIO2_2024_v1.1"

reported that its missing the FRC_ prefix

Edit: This applies to both roboRIO 1 & 2

**Comment by PeterJohnson** [comment]
Our version detector regex (https://github.com/wpilibsuite/GradleRIO/blob/main/src/main/java/edu/wpi/first/gradlerio/deploy/roborio/RoboRIO.java#L128) looks for a version that starts with `FRC_roboRIO`.

**Comment by sciencewhiz** [comment]
As a simpler workaround, you should be able to add `checkImage = false` to the roborio block in build.gradle.

**Comment by PeterJohnson** [comment]
Workaround implemented in WPILib Beta 2 release.

**Comment by Jm-Taylor** [comment]
Fixed in NI 2024 Beta Release 2 with v2.0 image.
